Adds config class
puppetlabs-operations/puppet-jmxtrans pull request #1
Opened 2016-11-17 18:58 UTC by petems

* Config class currently only contains configuration for `jmxtrans` service files, init.d and systemd
* Uses the service_provider fact available from stdlib

2016-11-17 21:46 UTC, danielparks requested changes
Just a couple of small things.

2016-11-17 21:46 UTC, danielparks commented on manifests/config.pp
> +          path        => $::path,
Huh. I haven't seen this before, and quick googling doesn't show it. Can you point me at docs or where this is defined?

2016-11-17 21:46 UTC, danielparks commented on manifests/init.pp
> +  Optional[Boolean] $manage_service_file = undef,
Seems like this should be `Boolean $manage_service_file = false,`.

2016-11-17 21:46 UTC, danielparks commented on manifests/config.pp
> +          content => epp('jmxtrans/jmxtrans.epp'),
It might be nice to change the name to clarify that this is an init file. (`jmxtrans/init/jmxtrans.epp`? `jmxtrans/jmxtrans.init.epp`?)

2016-11-17 21:46 UTC, danielparks commented on templates/jmxtrans.epp
> +RUN_AS_USER=jmxtrans
This should be parameterized.

2016-11-17 22:02 UTC, petems commented on manifests/config.pp
> +          path        => $::path,
It's a core fact: https://docs.puppet.com/facter/latest/core_facts.html#path

2016-11-17 22:02 UTC, petems commented on manifests/config.pp
> +          content => epp('jmxtrans/jmxtrans.epp'),
Good idea! 👍

2016-11-17 22:03 UTC, petems commented on manifests/init.pp
> +  Optional[Boolean] $manage_service_file = undef,
Yeah, that actually makes a lot more sense... I guess we could make it default to false, non-optional

2016-11-17 22:03 UTC, petems commented on templates/jmxtrans.epp
> +RUN_AS_USER=jmxtrans
Will do! 👍

2016-11-17 22:09 UTC, purplexa commented on manifests/config.pp
> +        file { '/etc/init.d/jmxtrans':
What's the use-case for this? AFAIK, both the RPM and DEB packages of jmxtrans include a platform-specific init script, so it's not clear the benefit to managing it here, and it adds maintenance burden if they make changes that affect the init script.

2016-11-17 22:09 UTC, purplexa commented on manifests/config.pp
> +          path        => $::path,
Elsewhere, we use the `$facts['path']` syntax, so for consistency, we should probably use that here.

2016-11-17 22:09 UTC, purplexa commented on manifests/init.pp
> +
Style: there should probably be an empty line between the `contain` lines and the dependency chaining rather than here, like

```
contain ...
contain ...
contain ...

Class... -> ...
Class... ~> ...
Class... ~> ...
```

2016-11-17 22:09 UTC, purplexa commented on templates/jmxtrans.service.epp
> +ExecStart=/usr/share/jmxtrans/bin/jmxtrans start
So, at least for version 259 (haven't checked 260), with the DEB package, the equivalent file is called `/usr/share/jmxtrans/bin/jmxtrans.sh` for reasons I don't know, and it straight up doesn't work if you don't set a handful of environment variables that lack defaults on that platform, so there may be a compatibility issue here.

2016-11-17 22:09 UTC, purplexa commented on templates/jmxtrans.service.epp
> +ExecStartPre=-/usr/bin/mkdir /run/jmxtrans/
Is there a particular reason you used `/run/jmxtrans/` in the `ExecStartPre` lines but `/var/run/jmxtrans/` in the PIDFile line? I don't think it matters on any relevant platform, just curious.

2016-11-17 22:09 UTC, purplexa commented on manifests/config.pp
> +        file { '/usr/lib/systemd/system/jmxtrans.service':
As I understand, this location is intended for placement by package managers, so I think the proper location here would be `/etc/systemd/system/jmxtrans.service`.

2016-11-17 22:09 UTC, thrnio commented on manifests/config.pp
> +    case $::service_provider {
Elsewhere, we use the `$facts['service_provider']` syntax, so for consistency, we should probably use that here.

2016-11-17 22:09 UTC, thrnio commented on manifests/config.pp
> +        file { '/etc/init.d/jmxtrans':
Oh, also, this init script won't work on the Debian build because it's way different and doesn't include the tanuki wrapper at all.

2016-11-17 22:09 UTC, thrnio commented on spec/classes/jmxtrans_spec.rb
> +        context 'jmxtrans class with manage_service_file true' do
There should also be the negative tests, that when `:manage_service_file => false`, it compiles but doesn't contain the relevant file resources.

2016-11-24 15:54 UTC, petems commented on spec/classes/jmxtrans_spec.rb
> +        context 'jmxtrans class with manage_service_file true' do
Fixed

2016-11-24 15:56 UTC, petems commented on templates/jmxtrans.service.epp
> +ExecStart=/usr/share/jmxtrans/bin/jmxtrans start
So, should this be platform dependant then? `/usr/share/jmxtrans/bin/jmxtrans.sh start` on Debian, `/usr/share/jmxtrans/bin/jmxtrans start` on RedHat?

2016-11-27 03:25 UTC, danielparks approved these changes
Thanks! +1

2017-01-12 22:14 UTC, merged